include: package:flutter_lints/flutter.yaml

plugins:
  anthem_analyzer_plugin:
    path: tools/anthem_analyzer_plugin
    diagnostics:
      invalid_union_assignment: error

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    prefer_single_quotes: true
    unnecessary_statements: true
