targets:
  $default:
    builders:
      anthem_codegen|anthemDartModelGeneratorBuilder:
        generate_for:
          - lib/*
          - lib/**/*
      anthem_codegen|cppModelBuilder:
        generate_for:
          - lib/*
          - lib/**/*
