targets:
  $default:
    builders:
      anthem_codegen:anthemDartModelGeneratorBuilder:
        generate_for:
          - lib/*
          - lib/**/*
      anthem_codegen:cppModelBuilder:
        generate_for:
          - lib/*
          - lib/**/*
      anthem_codegen:debugEnginePathGeneratorBuilder:
        generate_for:
          - lib/engine_api/engine_connector_desktop.dart
