[package]
name = "anthem_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
anthem_engine_model = { path = "./anthem_engine_model" }
bincode = "1.3.3"
interprocess = "1.1.1"
log = "0.4.14"
log4rs = { version = "1.0.0" }
