targets:
  $default:
    builders:
      anthem_codegen|anthemModelGeneratorBuilder:
        enabled: true

builders:
  anthemModelGeneratorBuilder:
    import: 'package:anthem_codegen/codegen.dart'
    builder_factories: ['anthemModelGeneratorBuilder']
    build_extensions: {'.dart': ['.anthem_model_generator.g.part']}
    auto_apply: dependents
    build_to: cache
    applies_builders: ['source_gen|combining_builder']
