/*
  Copyright (C) 2024 - 2026 Joshua Wade

  This file is part of Anthem.

  Anthem is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  Anthem is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with Anthem. If not, see <https://www.gnu.org/licenses/>.
*/

import 'package:anthem_codegen/generators/util/model_types.dart';
import 'package:anthem_codegen/generators/util/writer.dart';
import 'package:anthem_codegen/generators/util/model_class_info.dart';

import 'get_cpp_type.dart';

void writeModelSyncFnDeclaration(Writer writer) {
  writer.writeLine(
    'virtual void handleModelUpdate(ModelUpdateRequest& request, int fieldAccessIndex);',
  );
}

/// Generates a C++ function that takes a given update message, and uses it to
/// update the model described by [context].
///
/// The C++ method generated by this function will look something like this:
///
/// ```cpp
/// void MyModel::handleModelUpdate(ModelUpdateRequest& request, int fieldAccessIndex) {
///   if ((*request.fieldAccesses)[fieldAccessIndex]->fieldName == "myFirstField") {
///     this->myFirstField = std::stoll(request.serializedValue.value());
///   } else if ((*request.fieldAccesses)[fieldAccessIndex]->fieldName == "mySecondField") {
///     // etc...
///   }
/// }
/// ```
///
/// Anthem also uses code generation for our messaging system, so the
/// `ModelUpdateRequest` class is defined in Dart (see
/// `lib/engine_api/messages/model_sync.dart`) and generated into C++ as well,
/// into `messages/messages.h`. The C++ method generated by this function takes
/// a `ModelUpdateRequest`, and if that request is for a field that exists on
/// the model, it will update that field with the provided value. If it is
/// instead for a field on a child model, it will forward the request to that
/// child model.
String getModelSyncFn(ModelClassInfo context) {
  final writer = Writer();

  final fieldAccessIsFunctionCall =
      context.annotation?.generateCppWrapperClass == true;
  final parentheses = fieldAccessIsFunctionCall ? '()' : '';

  final baseSuffix = context.annotation?.cppBehaviorClassName != null
      ? 'Base'
      : '';

  writer.writeLine(
    'void ${context.annotatedClass.name}$baseSuffix::handleModelUpdate(ModelUpdateRequest& request, int fieldAccessIndex) {',
  );
  writer.incrementWhitespace();

  writer.writeLine('if (self.expired()) {');
  writer.incrementWhitespace();
  writer.writeLine(
    'std::cout << "Error updating model \\"${context.annotatedClass.name}\\": model has been deleted." << \'\\n\';',
  );
  writer.writeLine('return;');
  writer.decrementWhitespace();
  writer.writeLine('}');
  final selfPtrName = writer.nextIdentifier('selfPtr');
  final fieldNameNullableName = writer.nextIdentifier('fieldNameNullable');
  final fieldNameName = writer.nextIdentifier('fieldName');

  writer.writeLine('auto $selfPtrName = this->self.lock();');

  var noCasesGenerated = true;

  writer.writeLine(
    'auto& $fieldNameNullableName = (*request.fieldAccesses)[fieldAccessIndex]->fieldName;',
  );

  writer.writeLine('if (!$fieldNameNullableName.has_value()) {');
  writer.incrementWhitespace();
  writer.writeLine(
    'std::cout << "Error updating model \\"${context.annotatedClass.name}\\": field name is null." << \'\\n\';',
  );
  writer.writeLine('return;');
  writer.decrementWhitespace();
  writer.writeLine('}');

  writer.writeLine('auto& $fieldNameName = $fieldNameNullableName.value();');

  for (var MapEntry(key: fieldName, value: field) in context.fields.entries) {
    if (field.isModelConstant) {
      continue;
    }

    if (field.hideAnnotation?.cpp == true) {
      continue;
    }

    writer.writeLine(
      '${noCasesGenerated ? '' : 'else '}if ($fieldNameName == "$fieldName") {',
    );
    writer.incrementWhitespace();

    _writeUpdate(
      context: context,
      writer: writer,
      type: field.typeInfo,
      createFieldSetter: (value) => 'this->$fieldName$parentheses = $value;',
      observabilityNotifier:
          'this->${fieldName}Observers.notify(this->$fieldName$parentheses);',
      fieldAccessExpression: 'this->$fieldName$parentheses',
      parentAccessor: selfPtrName,
    );

    // If this was a raw field update, then we should notify the current model
    // that it has been updated.
    //
    // Note that this is very simplistic, and only handles setting fields to new
    // values. It doesn't allow observations for collection changes. This can be
    // added in the future if needed.
    writer.writeLine();
    writer.writeLine(
      'if (fieldAccessIndex == request.fieldAccesses->size() - 1) {',
    );
    writer.incrementWhitespace();
    writer.writeLine('this->processChange("$fieldName");');
    writer.decrementWhitespace();
    writer.writeLine('}');

    writer.decrementWhitespace();
    writer.writeLine('}');

    noCasesGenerated = false;
  }

  if (!noCasesGenerated) {
    writer.writeLine('else {');
    writer.incrementWhitespace();
    writer.writeLine(
      'std::cout << "Unexpected field name \\"" << $fieldNameName << "\\" on model \\"${context.annotatedClass.name}\\". This update will be ignored." << \'\\n\';',
    );
    writer.decrementWhitespace();
    writer.writeLine('}');
  }

  writer.decrementWhitespace();
  writer.writeLine('}');

  return writer.result.toString();
}

bool _shouldMoveTemporaryValue(ModelType type) {
  return switch (type) {
    IntModelType() ||
    DoubleModelType() ||
    NumModelType() ||
    BoolModelType() ||
    EnumModelType() ||
    ColorModelType() => false,
    StringModelType() ||
    ListModelType() ||
    MapModelType() ||
    CustomModelType() ||
    UnionModelType() ||
    UnknownModelType() => true,
  };
}

bool _supportsNestedAnthemModelAccess(ModelType type) {
  return type is CustomModelType ||
      type is ListModelType ||
      type is MapModelType;
}

bool _shouldSkipSubtypeOnWasm(ModelType type) {
  return type is CustomModelType &&
      type.modelClassInfo.annotation?.skipOnWasm == true;
}

void _writeInvalidAccessWarning({
  required Writer writer,
  required ModelType type,
  required ModelClassInfo context,
  required String fieldAccessExpression,
}) {
  writer.writeLine(
    'std::cout << "Invalid field access: \\"$fieldAccessExpression\\", on model \\"${context.annotatedClass.name}\\"" << \'\\n\';',
  );
  writer.writeLine(
    'std::cout << "The accessor \\"$fieldAccessExpression\\" does not point to an Anthem model or collection of Anthem models, so the update could not be forwarded." << \'\\n\';',
  );
  writer.writeLine(
    'std::cout << "\\"$fieldAccessExpression\\" is of type \\"${type.dartName}\\"." << \'\\n\';',
  );
}

void _writeSerializedValueNullCheck({
  required Writer writer,
  required String fieldAccessExpression,
  required ModelClassInfo context,
}) {
  writer.writeLine('if (!request.serializedValue.has_value()) {');
  writer.incrementWhitespace();
  writer.writeLine(
    'std::cout << "Error updating accessor \\"$fieldAccessExpression\\" on model \\"${context.annotatedClass.name}\\"." << \'\\n\';',
  );
  writer.writeLine(
    'std::cout << "Serialized value is null, but shouldn\'t be in this context." << \'\\n\';',
  );
  writer.writeLine('return;');
  writer.decrementWhitespace();
  writer.writeLine('}');
}

void _writeIndexCheckForPrimitive({
  required int fieldAccessIndexMod,
  required Writer writer,
  required ModelType type,
  required ModelClassInfo context,
  required String fieldAccessExpression,
}) {
  writer.writeLine(
    'if (request.fieldAccesses->size() > fieldAccessIndex + 1 + $fieldAccessIndexMod) {',
  );
  writer.incrementWhitespace();
  _writeInvalidAccessWarning(
    writer: writer,
    type: type,
    context: context,
    fieldAccessExpression: fieldAccessExpression,
  );
  writer.writeLine('return;');
  writer.decrementWhitespace();
  writer.writeLine('}');
}

void _writeUpdateTypeInvalidError({
  required Writer writer,
  required ModelClassInfo context,
  required String updateKind,
  required ModelType type,
  required String fieldAccessExpression,
}) {
  writer.writeLine(
    'std::cout << "Invalid update type for accessor \\"$fieldAccessExpression\\" on model \\"${context.annotatedClass.name}\\"" << \'\\n\';',
  );
  writer.writeLine(
    'std::cout << "Update type \\"$updateKind\\" is not valid for field \\"$fieldAccessExpression\\" of type ${type.toString()}." << \'\\n\';',
  );
}

/// Checks the result of the given JSON deserialization, and early returns if
/// there is one, along with printing the error.
void _writeJsonResultCheck({
  required Writer writer,
  required String resultVariable,
  required ModelClassInfo context,
  required String fieldAccessExpression,
}) {
  writer.writeLine('if (!$resultVariable.has_value()) {');
  writer.incrementWhitespace();
  writer.writeLine(
    'std::cout << "Error deserializing to field \\"$fieldAccessExpression\\" in model \\"${context.annotatedClass.name}\\":" << \'\\n\' << $resultVariable.error().what() << \'\\n\';',
  );
  writer.writeLine('return;');
  writer.decrementWhitespace();
  writer.writeLine('}');
}

String _writeJsonReadResult({
  required Writer writer,
  required ModelType type,
  required ModelClassInfo context,
  required String fieldAccessExpression,
  String nameStem = 'result',
}) {
  final resultVariable = writer.nextIdentifier(nameStem);
  writer.writeLine(
    'auto $resultVariable = rfl::json::read<${getCppType(type, context)}>(request.serializedValue.value());',
  );
  _writeJsonResultCheck(
    writer: writer,
    resultVariable: resultVariable,
    context: context,
    fieldAccessExpression: fieldAccessExpression,
  );

  return resultVariable;
}

/// Writes a single `if constexpr (...) { ... }` block for the union members
/// that can participate in Anthem's recursive model logic.
///
/// The generated C++ visitors usually want to do the same thing for every
/// model-like union case. For example:
/// - `Node.processor` should initialize whichever processor model is active
/// - a nested update like `processor.someField` should forward into whichever
///   processor model is active
///
/// Older codegen emitted one `if constexpr / else if constexpr` branch per
/// union member even though each branch had the same body. Clang-tidy then
/// flagged those as cloned branches. This helper collapses those cases into a
/// single condition like:
///
/// `if constexpr (is Foo || is Bar || is Baz) { shared_body(); }`
///
/// `subTypes` should already be filtered down to the union members that really
/// support recursive model access. Primitive cases like `int` should never be
/// included here because they do not have `initialize(...)` or
/// `handleModelUpdate(...)`.
///
/// The only complication is `skipOnWasm`: some union members exist on desktop
/// builds but are compiled out for Emscripten. We preserve that behavior by
/// splitting the condition into:
/// - members that are always available
/// - members that must sit behind `#ifndef __EMSCRIPTEN__`
void _writeUnionModelSubtypeBlock({
  required Writer writer,
  required String variantNameType,
  required List<ModelType> subTypes,
  required void Function() writeBody,
}) {
  final regularSubTypes = subTypes
      .where((t) => !_shouldSkipSubtypeOnWasm(t))
      .toList();
  final wasmSkippedSubTypes = subTypes.where(_shouldSkipSubtypeOnWasm).toList();

  if (regularSubTypes.isEmpty && wasmSkippedSubTypes.isEmpty) {
    return;
  }

  // If every eligible subtype is desktop-only, the whole block can disappear
  // on Emscripten instead of threading preprocessor guards through the
  // condition itself.
  final wrapWholeBlockInIfndef = regularSubTypes.isEmpty;

  if (wrapWholeBlockInIfndef) {
    writer.writeLine('#ifndef __EMSCRIPTEN__');
    writer.incrementWhitespace();
  }

  writer.writeLine('if constexpr (');
  writer.incrementWhitespace();

  var wroteCondition = false;

  void writeConditionLine(ModelType subType) {
    writer.writeLine(
      '${wroteCondition ? '|| ' : ''}std::is_same<$variantNameType, rfl::Literal<"${subType.dartName}">>()',
    );
    wroteCondition = true;
  }

  for (final subType in regularSubTypes) {
    writeConditionLine(subType);
  }

  // If we have a mix of always-available and desktop-only subtypes, only the
  // desktop-only tag checks need to be hidden from the WASM build.
  if (wasmSkippedSubTypes.isNotEmpty && !wrapWholeBlockInIfndef) {
    writer.writeLine('#ifndef __EMSCRIPTEN__');
    writer.incrementWhitespace();
  }

  for (final subType in wasmSkippedSubTypes) {
    writeConditionLine(subType);
  }

  if (wasmSkippedSubTypes.isNotEmpty && !wrapWholeBlockInIfndef) {
    writer.decrementWhitespace();
    writer.writeLine('#endif');
  }

  writer.decrementWhitespace();
  writer.writeLine(') {');
  writer.incrementWhitespace();
  writeBody();
  writer.decrementWhitespace();
  writer.writeLine('}');

  if (wrapWholeBlockInIfndef) {
    writer.decrementWhitespace();
    writer.writeLine('#endif');
  }
}

String _writeRequiredOptionalValueBinding({
  required Writer writer,
  required String optionalExpression,
  required String nameStem,
  required List<String> errorLines,
  String valueDeclaration = 'auto&',
}) {
  // Bind the optional to a stable local before checking/unwrapping it. This
  // keeps recursive codegen readable and avoids repeatedly re-evaluating the
  // same accessor chain in the emitted C++.
  final nullableValueName = writer.nextIdentifier('${nameStem}Nullable');
  final valueName = writer.nextIdentifier(nameStem);

  writer.writeLine('auto& $nullableValueName = $optionalExpression;');
  writer.writeLine('if (!$nullableValueName.has_value()) {');
  writer.incrementWhitespace();
  for (final errorLine in errorLines) {
    writer.writeLine(errorLine);
  }
  writer.writeLine('return;');
  writer.decrementWhitespace();
  writer.writeLine('}');
  writer.writeLine('$valueDeclaration $valueName = *$nullableValueName;');

  return valueName;
}

String _writeForwardableValueBinding({
  required Writer writer,
  required ModelType type,
  required String fieldAccessExpression,
  required String nameStem,
}) {
  // This helper is used when the update path goes deeper than the current
  // field. Example: if we are updating `loopPoints.startBeat`, we first need to
  // get the value of `loopPoints` and then continue generating code for
  // `startBeat`.
  //
  // For nullable fields, that means:
  // 1. Save the optional field expression in a local.
  // 2. Check whether it actually has a value.
  // 3. Unwrap it once and recurse using that unwrapped local.
  //
  // Doing this in one place keeps the recursive generator logic simpler and
  // avoids repeating long `.value()` chains in the emitted C++.
  if (!type.isNullable) {
    return fieldAccessExpression;
  }

  return _writeRequiredOptionalValueBinding(
    writer: writer,
    optionalExpression: fieldAccessExpression,
    nameStem: nameStem,
    errorLines: [
      'std::cout << "The value at accessor $fieldAccessExpression is null, so the update could not be forwarded." << \'\\n\';',
    ],
  );
}

({String fieldAccessVariable, String listIndexVariable})
_writeListFieldAccessBinding({
  required Writer writer,
  required int fieldAccessIndexMod,
  required String createFieldSetterExample,
}) {
  // List updates pull information out of the request message itself. For
  // example, an update like `notes[3]` stores that `3` inside
  // `request.fieldAccesses[...]`.
  //
  // This helper:
  // 1. Binds that request accessor entry to a local.
  // 2. Pulls out its `listIndex` once.
  // 3. Returns stable locals that the rest of the recursive list logic can
  //    reuse.
  //
  // That keeps the generated C++ simpler and avoids repeating
  // `(*request.fieldAccesses)[...]->listIndex.value()` everywhere.
  final fieldAccessVariable = writer.nextIdentifier('fieldAccess');
  writer.writeLine(
    'auto& $fieldAccessVariable = (*request.fieldAccesses)[fieldAccessIndex + 1 + $fieldAccessIndexMod];',
  );

  final listIndexVariable = _writeRequiredOptionalValueBinding(
    writer: writer,
    optionalExpression: '$fieldAccessVariable->listIndex',
    nameStem: 'listIndex',
    errorLines: [
      'std::cout << "Error processing list update for setter \\"$createFieldSetterExample\\": list index is null." << \'\\n\';',
    ],
    valueDeclaration: 'const auto&',
  );

  return (
    fieldAccessVariable: fieldAccessVariable,
    listIndexVariable: listIndexVariable,
  );
}

({String fieldAccessVariable, String deserializedKeyVariable})
_writeMapFieldAccessBinding({
  required Writer writer,
  required int fieldAccessIndexMod,
  required ModelType keyType,
}) {
  // Map updates work the same way, except the request stores a serialized map
  // key instead of a list index. We bind the request accessor once, deserialize
  // the key once, and then let the recursive map logic reuse those locals.
  final fieldAccessVariable = writer.nextIdentifier('fieldAccess');
  final deserializedKeyVariable = writer.nextIdentifier('deserializedKey');

  writer.writeLine(
    'auto& $fieldAccessVariable = (*request.fieldAccesses)[fieldAccessIndex + 1 + $fieldAccessIndexMod];',
  );
  _writeKeyDeserialize(
    writer: writer,
    keyExpression: '$fieldAccessVariable->serializedMapKey',
    keyType: keyType,
    outputVariable: deserializedKeyVariable,
  );

  return (
    fieldAccessVariable: fieldAccessVariable,
    deserializedKeyVariable: deserializedKeyVariable,
  );
}

String _writeInitializationBindingIfNullable({
  required Writer writer,
  required ModelType type,
  required String fieldAccessor,
  required String nameStem,
}) {
  // Initialization has the same nullable-access issue as update forwarding. If
  // a field is optional, open a scoped block with a stable unwrapped local and
  // let the caller emit initialization code against that local.
  if (!type.isNullable) {
    return fieldAccessor;
  }

  final nullableValueName = writer.nextIdentifier('${nameStem}Nullable');
  final valueName = writer.nextIdentifier(nameStem);

  writer.writeLine('auto& $nullableValueName = $fieldAccessor;');
  writer.writeLine('if ($nullableValueName.has_value()) {');
  writer.incrementWhitespace();
  writer.writeLine('auto& $valueName = *$nullableValueName;');

  return valueName;
}

void _closeInitializationBindingIfNullable({
  required Writer writer,
  required ModelType type,
}) {
  if (!type.isNullable) {
    return;
  }

  writer.decrementWhitespace();
  writer.writeLine('}');
}

/// Writes a field update for the given field.
///
/// The [fieldAccessExpression] parameter specifies the target to be modified,
/// as a C++ expression, and the [type] parameter specifies the type of the
/// field being updated.
///
/// As an example, a call to this function might look like:
///
/// ```dart
/// writeUpdate(
///   type: IntModelType(),
///   modificationTarget: 'this->myStringField',
/// );
/// ```
///
/// This might generate code like:
///
/// ```cpp
/// // (A few validation checks on the request)
/// this->myStringField = std::stoll(request.serializedValue.value());
/// ```
///
/// If the field is a custom model, then this will also generate code to
/// forward appropriate requests to the child model. If the field is instead
/// a collection, then this function will recursively call itself to
/// generate code to update the collection. For example, given a Map<String,
/// int>, the generated code might look like:
///
/// ```cpp
/// // (A few validation checks on the request)
/// if (request.fieldAccesses->size() == fieldAccessIndex + 1) {
///   // After generating up to this point, the function will call itself
///   // recursively like so:
///   // writeUpdate(
///   //   type: IntModelType(),
///   //   modificationTarget: 'this->myMapField[(*request.fieldAccesses)[fieldAccessIndex + 1]->serializedValue.value()]',
///   // );
/// }
/// // Etc...
/// ```
void _writeUpdate({
  required Writer writer,
  required ModelType type,
  required String Function(String valueExpression) createFieldSetter,
  required String observabilityNotifier,
  required String fieldAccessExpression,
  required ModelClassInfo context,
  required String parentAccessor,
  int fieldAccessIndexMod = 0,
  bool isCollectionSetter = false,
  bool allowNestedAccess = true,
}) {
  switch (type) {
    case StringModelType _ ||
        IntModelType _ ||
        DoubleModelType _ ||
        NumModelType _ ||
        BoolModelType _ ||
        EnumModelType _ ||
        ColorModelType _:
      _writeIndexCheckForPrimitive(
        writer: writer,
        context: context,
        type: type,
        fieldAccessIndexMod: fieldAccessIndexMod,
        fieldAccessExpression: fieldAccessExpression,
      );
      _writeSerializedValueNullCheck(
        writer: writer,
        fieldAccessExpression: fieldAccessExpression,
        context: context,
      );

      final resultVariable = _writeJsonReadResult(
        writer: writer,
        type: type,
        context: context,
        fieldAccessExpression: fieldAccessExpression,
      );
      writer.writeLine(createFieldSetter('$resultVariable.value()'));
      writer.writeLine(observabilityNotifier);

      break;
    case ListModelType():
      // If the field is a list and this is *not* the last accessor in the
      // chain, then one of the two following things is true:
      //  1. The request is to add, set or remove a specific value in the list,
      //     in which case we should handle it by either adding, setting or
      //     removing the value.
      //  2. The request is to update some distant child whose parent lives in
      //     this list, in which case we should forward the request to the
      //     child.
      //
      // This if statement will be true if this concerns a specific index in the
      // list. This is because fieldAccessIndex refers to the index in the
      // accessor list that identifies the list itself, whereas fieldAccessIndex
      // + 1 refers to the index in the accessor list that identifies a
      // specific item in the list. If the list contains an item for
      // fieldAccessIndex + 1, then this is a request to update a specific item
      // in the list, or a request for a distant child of that item.
      writer.writeLine(
        'if (fieldAccessIndex + 1 + $fieldAccessIndexMod < request.fieldAccesses->size()) {',
      );
      writer.incrementWhitespace();
      final collectionAccessExpression = _writeForwardableValueBinding(
        writer: writer,
        type: type,
        fieldAccessExpression: fieldAccessExpression,
        nameStem: 'listValue',
      );
      final access = _writeListFieldAccessBinding(
        writer: writer,
        fieldAccessIndexMod: fieldAccessIndexMod,
        createFieldSetterExample: createFieldSetter('[value here]'),
      );

      writer.writeLine(
        'if (request.updateKind == FieldUpdateKind::remove && request.fieldAccesses->size() - 1 == fieldAccessIndex + 1 + $fieldAccessIndexMod) {',
      );
      writer.incrementWhitespace();
      writer.writeLine(
        '$collectionAccessExpression->erase($collectionAccessExpression->begin() + ${access.listIndexVariable});',
      );
      writer.decrementWhitespace();
      writer.writeLine(
        '} else if (request.updateKind == FieldUpdateKind::add && request.fieldAccesses->size() - 1 == fieldAccessIndex + 1 + $fieldAccessIndexMod) {',
      );
      writer.incrementWhitespace();
      _writeSerializedValueNullCheck(
        writer: writer,
        fieldAccessExpression: fieldAccessExpression,
        context: context,
      );
      final itemResultVariable = writer.nextIdentifier('itemResult');
      writer.writeLine(
        '${getCppType(type.itemType, context)} $itemResultVariable;',
      );
      _writeUpdate(
        context: context,
        writer: writer,
        type: type.itemType,
        fieldAccessExpression: itemResultVariable,
        createFieldSetter: (value) => '$itemResultVariable = $value;',
        observabilityNotifier: '',
        fieldAccessIndexMod: fieldAccessIndexMod + 1,
        parentAccessor: collectionAccessExpression,
        allowNestedAccess: false,
      );
      final itemInsertValue = _shouldMoveTemporaryValue(type.itemType)
          ? 'std::move($itemResultVariable)'
          : itemResultVariable;
      writer.writeLine(
        '$collectionAccessExpression->insert($collectionAccessExpression->begin() + ${access.listIndexVariable}, $itemInsertValue);',
      );
      writer.decrementWhitespace();
      writer.writeLine('} else {');
      writer.incrementWhitespace();
      // This will either set the field in the list, or forward the request to
      // the child model represented by the field in the list.
      _writeUpdate(
        context: context,
        writer: writer,
        type: type.itemType,
        fieldAccessExpression:
            '(*$collectionAccessExpression)[${access.listIndexVariable}]',
        createFieldSetter: (value) =>
            '(*$collectionAccessExpression)[${access.listIndexVariable}] = $value;',
        observabilityNotifier: '',
        fieldAccessIndexMod: fieldAccessIndexMod + 1,
        parentAccessor: collectionAccessExpression,
        isCollectionSetter: true,
      );
      writer.decrementWhitespace();
      writer.writeLine('}');

      // If this *is* the last accessor in the chain, then the provided JSON is
      // the new value for the entire list, and we should deserialize it into
      // this field.
      writer.decrementWhitespace();
      writer.writeLine('} else {');
      writer.incrementWhitespace();
      _writeSerializedValueNullCheck(
        writer: writer,
        fieldAccessExpression: fieldAccessExpression,
        context: context,
      );

      final resultVariable = _writeJsonReadResult(
        writer: writer,
        type: type,
        context: context,
        fieldAccessExpression: fieldAccessExpression,
      );
      writer.writeLine(createFieldSetter('std::move($resultVariable.value())'));
      writer.writeLine(observabilityNotifier);
      writeParentSetterForType(
        writer: writer,
        type: type,
        fieldAccessor: fieldAccessExpression,
        parentAccessor: parentAccessor,
      );

      writer.decrementWhitespace();
      writer.writeLine('}');
      break;
    case MapModelType():
      // If the field is a map and this is *not* the last accessor in the chain,
      // then one of the two following things is true:
      //  1. The request is to set or remove a specific value in the map, in
      //     which case we should handle it by either setting or removing the
      //     value.
      //  2. The request is to update some distant child whose parent lives in
      //     this map, in which case we should forward the request to the child.
      //
      // This if statement will be true if this concerns a specific key in the
      // map. This is because fieldAccessIndex refers to the index in the
      // accessor list that identifies the map itself, whereas fieldAccessIndex
      // + 1 refers to the index in the accessor list that identifies a specific
      // item in that map. If the list contains an item for fieldAccessIndex +
      // 1, then this is a request to update a specific item in the map, or a
      // request for a distant child of that item.
      writer.writeLine(
        'if (fieldAccessIndex + 1 + $fieldAccessIndexMod < request.fieldAccesses->size()) {',
      );
      writer.incrementWhitespace();
      final collectionAccessExpression = _writeForwardableValueBinding(
        writer: writer,
        type: type,
        fieldAccessExpression: fieldAccessExpression,
        nameStem: 'mapValue',
      );
      final access = _writeMapFieldAccessBinding(
        writer: writer,
        fieldAccessIndexMod: fieldAccessIndexMod,
        keyType: type.keyType,
      );

      writer.writeLine(
        'if (request.updateKind == FieldUpdateKind::remove && request.fieldAccesses->size() - 1 == fieldAccessIndex + 1 + $fieldAccessIndexMod) {',
      );
      writer.incrementWhitespace();
      writer.writeLine(
        '$collectionAccessExpression->erase(${access.deserializedKeyVariable});',
      );
      writer.decrementWhitespace();
      writer.writeLine(
        '} else if (request.updateKind == FieldUpdateKind::add && request.fieldAccesses->size() - 1 == fieldAccessIndex + 1 + $fieldAccessIndexMod) {',
      );
      writer.incrementWhitespace();
      // "Add" is only valid for list. Should use "set" instead.
      _writeUpdateTypeInvalidError(
        writer: writer,
        context: context,
        updateKind: 'add',
        type: type,
        fieldAccessExpression: fieldAccessExpression,
      );
      writer.decrementWhitespace();
      writer.writeLine('} else {');
      writer.incrementWhitespace();

      // This will handle setting the value or forwarding the value, depending
      // on which is needed. We only have to explicitly handle deletion here,
      // which we do above.
      _writeUpdate(
        context: context,
        writer: writer,
        type: type.valueType,
        fieldAccessExpression:
            '$collectionAccessExpression->at(${access.deserializedKeyVariable})',
        createFieldSetter: (value) =>
            '$collectionAccessExpression->insert_or_assign(${access.deserializedKeyVariable}, $value);',
        observabilityNotifier: '',
        fieldAccessIndexMod: fieldAccessIndexMod + 1,
        parentAccessor: collectionAccessExpression,
        isCollectionSetter: true,
      );

      writer.decrementWhitespace();
      writer.writeLine('}');

      // If this *is* the last accessor in the chain, then the provided JSON is
      // the new value for the entire map, and we should deserialize it into
      // this field.
      writer.decrementWhitespace();
      writer.writeLine('} else {');
      writer.incrementWhitespace();
      _writeSerializedValueNullCheck(
        writer: writer,
        fieldAccessExpression: fieldAccessExpression,
        context: context,
      );

      final resultVariable = _writeJsonReadResult(
        writer: writer,
        type: type,
        context: context,
        fieldAccessExpression: fieldAccessExpression,
      );
      writer.writeLine(createFieldSetter('std::move($resultVariable.value())'));
      writer.writeLine(observabilityNotifier);
      writeParentSetterForType(
        writer: writer,
        type: type,
        fieldAccessor: fieldAccessExpression,
        parentAccessor: parentAccessor,
      );

      writer.decrementWhitespace();
      writer.writeLine('}');
      break;
    case CustomModelType() || UnionModelType() || UnknownModelType():
      if (!allowNestedAccess) {
        // This path is used when we are materializing a temporary value for a
        // list "add" operation before inserting it into the list. The outer
        // list-add branch only runs when the accessor chain already ends at the
        // new list element itself, so there is no valid deeper child access to
        // forward here. Even for model-valued list items, we should only
        // deserialize the inserted value, not generate nested
        // temporary-value forwarding logic.
        _writeSerializedValueNullCheck(
          writer: writer,
          fieldAccessExpression: fieldAccessExpression,
          context: context,
        );

        final resultVariable = _writeJsonReadResult(
          writer: writer,
          type: type,
          context: context,
          fieldAccessExpression: fieldAccessExpression,
        );
        writer.writeLine(
          createFieldSetter('std::move($resultVariable.value())'),
        );
        writer.writeLine(observabilityNotifier);

        if (!isCollectionSetter) {
          writeParentSetterForType(
            writer: writer,
            type: type,
            fieldAccessor: fieldAccessExpression,
            parentAccessor: parentAccessor,
          );
        }

        break;
      }

      // If this field is a custom model and this is the last accessor in the
      // chain, then we should deserialize the provided JSON into this field.
      writer.writeLine(
        'if (request.fieldAccesses->size() == fieldAccessIndex + 1 + $fieldAccessIndexMod) {',
      );
      writer.incrementWhitespace();
      _writeSerializedValueNullCheck(
        writer: writer,
        fieldAccessExpression: fieldAccessExpression,
        context: context,
      );

      final resultVariable = _writeJsonReadResult(
        writer: writer,
        type: type,
        context: context,
        fieldAccessExpression: fieldAccessExpression,
      );
      writer.writeLine(createFieldSetter('std::move($resultVariable.value())'));
      writer.writeLine(observabilityNotifier);

      // If we're setting inside a collection (e.g. someList[someIndex] =
      // deserializedValue), then we don't want to initialize the newly created
      // model because the list will do that for us.
      if (!isCollectionSetter) {
        // ... Otherwise, this is a raw setter (e.g. this->someField =
        // someValue), and we need to initialize the model.
        writeParentSetterForType(
          writer: writer,
          type: type,
          fieldAccessor: fieldAccessExpression,
          parentAccessor: parentAccessor,
        );
      }

      writer.decrementWhitespace();

      // If this field is a custom model and this is not the last accessor in
      // the chain, then we should forward the update to the child.
      writer.writeLine('} else {');
      writer.incrementWhitespace();
      final resolvedFieldAccessExpression = _writeForwardableValueBinding(
        writer: writer,
        type: type,
        fieldAccessExpression: fieldAccessExpression,
        nameStem: 'childValue',
      );

      if (type is UnionModelType) {
        // https://rfl.getml.com/variants_and_tagged_unions/#stdvariant-or-rflvariant-externally-tagged
        // See the visitor pattern example for how this is being parsed. This is
        // externally tagged, which is described there as well.
        final handleVariantName = writer.nextIdentifier('handleVariant');
        final variantFieldName = writer.nextIdentifier('variantField');
        final variantNameType = writer.nextIdentifier('variantName');
        final nestedModelSubTypes = type.subTypes
            .where(_supportsNestedAnthemModelAccess)
            .toList();
        writer.writeLine(
          'const auto $handleVariantName = [&](const auto& $variantFieldName) {',
        );
        writer.incrementWhitespace();
        writer.writeLine(
          'using $variantNameType = typename std::decay_t<decltype($variantFieldName)>::Name;',
        );

        _writeUnionModelSubtypeBlock(
          writer: writer,
          variantNameType: variantNameType,
          subTypes: nestedModelSubTypes,
          writeBody: () {
            writer.writeLine(
              '$variantFieldName.value()->handleModelUpdate(request, fieldAccessIndex + 1 + $fieldAccessIndexMod);',
            );
          },
        );

        writer.decrementWhitespace();
        writer.writeLine('};');

        writer.writeLine(
          'rfl::visit($handleVariantName, $resolvedFieldAccessExpression);',
        );
      } else {
        writer.writeLine(
          '$resolvedFieldAccessExpression->handleModelUpdate(request, fieldAccessIndex + 1 + $fieldAccessIndexMod);',
        );
      }

      writer.decrementWhitespace();
      writer.writeLine('}');

      break;
  }
}

void _writeKeyDeserialize({
  required Writer writer,
  required String keyExpression,
  required ModelType keyType,
  required String outputVariable,
}) {
  if (!keyType.canBeMapKey) {
    throw ArgumentError(
      'The provided key type, ${keyType.dartName}, cannot be used as a map key.',
    );
  }

  final serializedKeyValue = _writeRequiredOptionalValueBinding(
    writer: writer,
    optionalExpression: keyExpression,
    nameStem: 'serializedMapKey',
    errorLines: [
      'std::cout << "Error deserializing map key: key is null." << \'\\n\';',
    ],
    valueDeclaration: 'const auto&',
  );

  switch (keyType) {
    case StringModelType():
      if (keyType.isNullable) {
        writer.writeLine('std::optional<std::string> $outputVariable;');
        writer.writeLine('if ($serializedKeyValue == "null") {');
        writer.incrementWhitespace();
        writer.writeLine('$outputVariable = std::nullopt;');
        writer.decrementWhitespace();
        writer.writeLine('} else {');
        writer.incrementWhitespace();
        writer.writeLine(
          '$outputVariable = std::optional<std::string>($serializedKeyValue.substr(1, $serializedKeyValue.size() - 2));',
        );
        writer.decrementWhitespace();
        writer.writeLine('}');
      } else {
        writer.writeLine(
          'auto $outputVariable = $serializedKeyValue.substr(1, $serializedKeyValue.size() - 2);',
        );
      }
      break;
    case IntModelType():
      if (keyType.isNullable) {
        writer.writeLine('std::optional<int64_t> $outputVariable;');
        writer.writeLine('if ($serializedKeyValue == "null") {');
        writer.incrementWhitespace();
        writer.writeLine('$outputVariable = std::nullopt;');
        writer.decrementWhitespace();
        writer.writeLine('} else {');
        writer.incrementWhitespace();
        writer.writeLine(
          '$outputVariable = std::optional<int64_t>(std::stoll($serializedKeyValue));',
        );
        writer.decrementWhitespace();
        writer.writeLine('}');
      } else {
        writer.writeLine(
          'auto $outputVariable = std::stoll($serializedKeyValue);',
        );
      }

      break;
    case DoubleModelType() || NumModelType():
      if (keyType.isNullable) {
        writer.writeLine('std::optional<double> $outputVariable;');
        writer.writeLine('if ($serializedKeyValue == "null") {');
        writer.incrementWhitespace();
        writer.writeLine('$outputVariable = std::nullopt;');
        writer.decrementWhitespace();
        writer.writeLine('} else {');
        writer.incrementWhitespace();
        writer.writeLine(
          '$outputVariable = std::optional<double>(std::stod($serializedKeyValue));',
        );
        writer.decrementWhitespace();
        writer.writeLine('}');
      } else {
        writer.writeLine(
          'auto $outputVariable = std::stod($serializedKeyValue);',
        );
      }

      break;
    case BoolModelType():
      if (keyType.isNullable) {
        writer.writeLine('std::optional<bool> $outputVariable;');
        writer.writeLine('if ($serializedKeyValue == "null") {');
        writer.incrementWhitespace();
        writer.writeLine('$outputVariable = std::nullopt;');
        writer.decrementWhitespace();
        writer.writeLine('} else {');
        writer.incrementWhitespace();
        writer.writeLine(
          '$outputVariable = std::optional<bool>($serializedKeyValue == "true");',
        );
        writer.decrementWhitespace();
        writer.writeLine('}');
      } else {
        writer.writeLine(
          'auto $outputVariable = $serializedKeyValue == "true";',
        );
      }

      break;
    case EnumModelType():
      throw UnimplementedError(
        'Enums are not yet supported as map keys. This can be implemented in the future if the need arises.',
      );
    case ListModelType() ||
        MapModelType() ||
        ColorModelType() ||
        CustomModelType() ||
        UnknownModelType() ||
        UnionModelType():
      throw Exception(
        'These types should not be marked as map keys, and so should be caught above. This is a bug.',
      );
  }
}

// Writes (accessor)->initialize(self, parent), if necessary.
void writeParentSetterForType({
  required Writer writer,
  required ModelType type,
  required String fieldAccessor,
  required String parentAccessor,
}) {
  final shouldWrite =
      type is CustomModelType ||
      type is ListModelType ||
      type is MapModelType ||
      type is UnionModelType;
  final resolvedFieldAccessor = shouldWrite
      ? _writeInitializationBindingIfNullable(
          writer: writer,
          type: type,
          fieldAccessor: fieldAccessor,
          nameStem: 'initializedChild',
        )
      : fieldAccessor;

  if (type is CustomModelType ||
      type is ListModelType ||
      type is MapModelType) {
    writer.writeLine(
      '$resolvedFieldAccessor->initialize($resolvedFieldAccessor, $parentAccessor);',
    );
  } else if (type is UnionModelType) {
    final variantItemName = writer.nextIdentifier('variantItem');
    final variantNameType = writer.nextIdentifier('variantName');
    final initializedSubTypes = type.subTypes
        .where(_supportsNestedAnthemModelAccess)
        .toList();

    writer.writeLine('rfl::visit([&](auto& $variantItemName) {');
    writer.incrementWhitespace();

    writer.writeLine(
      'using $variantNameType = typename std::decay_t<decltype($variantItemName)>::Name;',
    );

    _writeUnionModelSubtypeBlock(
      writer: writer,
      variantNameType: variantNameType,
      subTypes: initializedSubTypes,
      writeBody: () {
        writer.writeLine(
          '$variantItemName.value()->initialize($variantItemName.value(), $parentAccessor);',
        );
      },
    );

    writer.decrementWhitespace();
    writer.writeLine('}, $resolvedFieldAccessor);');
  }

  if (shouldWrite) {
    _closeInitializationBindingIfNullable(writer: writer, type: type);
  }
}

/// Writes code to set the parent fields for all children to this.
///
/// This will be written to the constructor of the parent class.
void _writeParentSettersForInitializeFn({
  required Writer writer,
  required ModelClassInfo context,
}) {
  if (context.annotation?.generateCppWrapperClass != true) {
    return;
  }

  for (var MapEntry(key: fieldName, value: field) in context.fields.entries) {
    if (field.hideAnnotation?.cpp == true) {
      continue;
    }

    final type = field.typeInfo;

    writeParentSetterForType(
      writer: writer,
      type: type,
      fieldAccessor: 'this->$fieldName()',
      parentAccessor: 'this->self.lock()',
    );
  }
}

String getInitializeFn(ModelClassInfo context) {
  final writer = Writer();

  final className = context.annotatedClass.name;
  final baseSuffix = context.annotation?.cppBehaviorClassName != null
      ? 'Base'
      : '';

  writer.writeLine(
    'void $className$baseSuffix::initialize(std::shared_ptr<AnthemModelBase> selfModel, std::shared_ptr<AnthemModelBase> parentModel) {',
  );
  writer.incrementWhitespace();
  writer.writeLine('AnthemModelBase::initialize(selfModel, parentModel);');
  writer.writeLine();

  _writeParentSettersForInitializeFn(writer: writer, context: context);

  writer.decrementWhitespace();
  writer.writeLine('}');

  return writer.result.toString();
}

/// Returns a list of imports that are needed for the cpp file of the given
/// model.
///
/// The header file will contain imports for any generated model files. The only
/// imports that we need are for custom models that use a custom implementation
/// subclass. The custom subclass will be forward-declared in the header file,
/// but we need to include the actual implementation in the cpp file to avoid
/// circular dependencies.
Iterable<String> getCppFileImports(ModelClassInfo context) {
  final typesThatNeedImports = <ModelClassInfo>{};

  if (context.annotation?.cppBehaviorClassIncludePath != null) {
    typesThatNeedImports.add(context);
  }

  void process(ModelType type) {
    switch (type) {
      case CustomModelType():
        if (type.modelClassInfo.annotation?.cppBehaviorClassIncludePath !=
            null) {
          typesThatNeedImports.add(type.modelClassInfo);
        }

        // Reflect-cpp is based on compile-time reflection. When it
        // deserializes a model (e.g. ProjectModel), it will need to have
        // access to the types of all fields in that model, but also of all
        // fields in any child models. This means that we need to recursively
        // process all child models to ensure that, if they have a custom
        // implementation, that implementation is included in the cpp file.
        for (var MapEntry(key: _, value: field)
            in type.modelClassInfo.fields.entries) {
          process(field.typeInfo);
        }

        break;
      case ListModelType():
        process(type.itemType);
        break;
      case MapModelType():
        process(type.keyType);
        process(type.valueType);
        break;
      case UnionModelType type:
        for (final subType in type.subTypes) {
          process(subType);
        }
        break;
      default:
        break;
    }
  }

  for (var MapEntry(key: _, value: field) in context.fields.entries) {
    if (field.hideAnnotation?.cpp == true) {
      continue;
    }

    final type = field.typeInfo;

    process(type);
  }

  return typesThatNeedImports.map(
    (info) => '#include "${info.annotation!.cppBehaviorClassIncludePath}"',
  );
}
