name: anthem_analyzer_plugin
description: Anthem static analysis rules.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=3.11.0 <4.0.0"

resolution: workspace

dependencies:
  analysis_server_plugin: ^0.3.7
  analyzer: ^12.1.0

dev_dependencies:
  analyzer_testing: ^0.2.5
  lints: ^6.0.0
  test: ^1.26.0
  test_reflective_loader: ^0.4.0
