name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
          - os: ubuntu-24.04-arm
            arch: arm64

    steps:
      - name: Initialize project
        uses: ./.github/actions/shared-init

      - name: Build engine
        run: dart run anthem:cli engine build --release

      - name: Build Flutter
        run: flutter build linux --verbose --release

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: anthem-linux-${{ matrix.arch }}
          path: build/linux/${{ matrix.arch }}/release/bundle

  build-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            arch: arm64
          - os: macos-15-intel
            arch: x64

    steps:
      - name: Initialize project
        uses: ./.github/actions/shared-init

      - name: Build engine
        run: dart run anthem:cli engine build --release

      - name: Build Flutter
        run: flutter build macos --verbose --release

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: anthem-macos-${{ matrix.arch }}
          # https://github.com/actions/upload-artifact#upload-using-multiple-paths-and-exclusions
          # If a wildcard pattern is used, the path hierarchy will start with the first wildcard pattern
          path: build/macos/Build/Products/Release/*.app

  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            arch: x64
          - os: windows-11-arm
            arch: arm64

    steps:
      - name: Initialize project
        uses: ./.github/actions/shared-init

      - name: Build engine
        run: dart run anthem:cli engine build --release

      - name: Build Flutter
        run: flutter build windows --verbose --release

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: anthem-windows-${{ matrix.arch }}
          # As of writing, Flutter on Windows currently builds x64, as Dart does
          # not support arm64 on Windows yet. So, both the x64 and arm64 builds
          # are built as x64, and are output to the x64 folder. If (hopefully
          # when) this changes, the path here would look like the Linux path
          # below.
          path: build/windows/x64/runner/Release

  build-wasm:
    runs-on: ubuntu-latest

    steps:
      - name: Initialize project
        uses: ./.github/actions/shared-init

      - name: Set up Emscripten
        uses: emscripten-core/setup-emsdk@v16

      - name: Build engine
        run: dart run anthem:cli engine build --release --wasm

      - name: Build Flutter
        run: flutter build web --verbose --release --wasm

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Deploy web build to CloudFlare Pages
        run: |
          npm i -g wrangler@latest
          wrangler pages deploy build/web --project-name=anthem-audio --branch=${{ github.ref_name }} --commit-dirty=true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
